builds:
  - main: ./
    binary: nagocheck
    flags: -a -tags netgo
    ldflags: -s -w -X main.BuildVersion={{.Version}} -X main.BuildCommit={{.Commit}} -X main.BuildDate={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - 386
      - amd64
      - arm

    goarm:
      - 6
      - 7

archives:
  - format: tar.gz
    wrap_in_directory: true

nfpm:
  vendor: Pascal Mathis
  maintainer: SnapServ Packaging Team <packaging@snapserv.net>
  homepage: https://github.com/snapserv/nagocheck
  description: Reliable and lightweight Nagios plugins written in Go
  license: GPL-3.0
  bindir: /usr/bin
  formats:
    - deb
    - rpm
