builds:
  - main: ./
    binary: nagopher-checks
    flags: -a -tags netgo
    ldflags: -s -w

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64

nfpm:
  vendor: Pascal Mathis
  maintainer: Pascal Mathis <mail@pascalmathis.com>
  homepage: https://www.pascalmathis.com/
  description: Reliable and lightweight Nagios plugins written in Go
  license: GPL-3.0
  bindir: /usr/bin
  formats:
    - deb
    - rpm
