builds:
  - main: ./
    binary: nagopher-checks
    flags: -a -tags netgo
    ldflags: -s -w

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - 386
      - amd64
      - arm

    goarm:
      - 6
      - 7

archive:
  format: tar.gz
  wrap_in_directory: true

nfpm:
  vendor: Pascal Mathis
  maintainer: Pascal Mathis <ppmathis@noreply.smx.li>
  homepage: https://github.com/snapserv/nagopher-checks
  description: Reliable and lightweight Nagios plugins written in Go
  license: GPL-3.0
  bindir: /usr/bin
  formats:
    - deb
    - rpm
