os: linux
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

install:
  - make devel-deps

script:
  - make lint
  - make test
  # TODO: - make coverage

deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
      go: 1.10.x
