os: linux
language: go
env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - rpm

matrix:
  include:
    - go: 1.12.x
      env: NAGOCHECK_DEPLOY=1
    - go: 1.11.x

install:
  - make devel-deps

script:
  - make lint
  - make test

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $NAGOCHECK_DEPLOY = 1
