os: linux
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

install:
  - make devel-deps

script:
  - make lint
  - make test
  # TODO: - make coverage

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.10(\.[0-9]+)?$
