os: linux
language: go

addons:
  apt:
    packages:
      - rpm

matrix:
  include:
    - go: 1.9.x
    - go: 1.10.x
      env: NAGOCHECK_DEPLOY=1

install:
  - make devel-deps

script:
  - make lint
  - make test

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $NAGOCHECK_DEPLOY = 1
